import type React from "react"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { ThemeProvider } from "@/components/theme-provider"
import { Navbar } from "@/components/navbar"
import { Footer } from "@/components/footer"

const inter = Inter({ subsets: ["latin"] })

const keywords = [
  "BIPS Classes", "Digital Marketing course", "Spoken English classes","Competitive exam preparation", "Best coaching institute", "Online education","Career guidance", "Skill development", "Professional training","SEO training", "Social media marketing", "Content writing course","English speaking course", "Bank exam preparation", "SSC coaching","UPSC preparation", "Government job training", "IELTS coaching","TOEFL classes", "Personality development", "Communication skills","Google Ads certification", "Email marketing", "Affiliate marketing","PPC training", "Analytics course", "WordPress training","E-commerce marketing", "Online certification courses", "Placement assistance","Affordable education", "Expert faculty", "Practical training","Industry-relevant curriculum", "Study materials", "Mock tests","Result-oriented coaching", "Flexible timings", "Weekend batches","Online classes", "Offline classes", "Hybrid learning","Career advancement courses", "Job oriented training", "Professional certification","Search Engine Optimization", "Facebook Ads Course", "Instagram Marketing","YouTube SEO", "LinkedIn Marketing", "Twitter Ads", "Google Analytics","Google My Business", "Local SEO", "On-Page SEO", "Off-Page SEO","Technical SEO", "Keyword Research", "Backlink Strategy", "Content Strategy","Copywriting Course", "Video Marketing", "Influencer Marketing","Digital Branding", "Online Reputation Management", "Marketing Automation","Growth Hacking", "Conversion Rate Optimization", "Landing Page Design","Lead Generation", "Sales Funnel Training", 
  "Google Tag Manager","Data Analytics", "UI/UX Design Course", "Graphic Design Course","Canva Training", "Adobe Photoshop Course", "Web Development Course","HTML/CSS Training", "JavaScript Course", "Python for Marketing","ChatGPT for Digital Marketing", "AI Marketing Tools", "Meta Ads","TikTok Marketing", "Pinterest Marketing", "WhatsApp Business","Telegram Marketing", "Digital Marketing Certification", "Google Shopping Ads","Programmatic Advertising", "Native Advertising", "Retargeting Course","Customer Journey Mapping", "Marketing Psychology", "Brand Management","CRO Certification", "Marketing Strategy Course", "Freelancing Course","Remote Digital Jobs", "E-commerce SEO", "Shopify Marketing","Amazon FBA Training", "Dropshipping Course", "Print on Demand","CPA Marketing", "White Hat SEO", "Black Hat SEO", "Voice Search Optimization","Mobile Marketing", "App Store Optimization", "Google Search Console","Bing Webmaster Tools", "Schema Markup", "Rich Snippets","Google Data Studio", "Heatmap Analysis", "A/B Testing Course","Marketing Funnel", "Cold Email Marketing", "Sales Copywriting","Storytelling in Marketing", "Neuromarketing", "Color Psychology","Typography Course", "Logo Design", "Brand Identity", "Marketing Laws","Google Algorithm Updates", "SEO Audit", "Website Speed Optimization","Core Web Vitals", "Google Penalty Recovery", "Disavow Links","Guest Posting", "Blog Outreach", "Skyscraper Technique","Digital PR", "Podcast Marketing", "Webinar Marketing","Live Streaming Marketing", "Community Management", "Crisis Management",
  "Employer Branding", "HR Digital Marketing", "B2B Marketing","B2C Marketing", "Local Business Marketing", "Franchise Marketing","Nonprofit Marketing", "Educational Marketing", "Hospitality Marketing","Real Estate Marketing", "Healthcare Marketing", "Legal Marketing","Finance Marketing", "Cryptocurrency Marketing", "NFT Marketing","Metaverse Marketing", "AR/VR Marketing", "3D Advertising","Interactive Content", "Quizzes Marketing", "Polls Marketing","Surveys Marketing", "Chatbot Marketing", "Voice Assistant Marketing","Marketing Ethics", "GDPR Compliance", "CCPA Compliance","Accessibility in Marketing", "Inclusive Marketing", "Sustainable Marketing","Green Marketing", "Cause Marketing", "Corporate Social Responsibility","Marketing Budgeting", "ROI Measurement", "KPI Tracking","Marketing Dashboard", "Marketing Attribution", "Multi-Touch Attribution","Marketing Mix Modeling", "Predictive Analytics", "AI Content Creation","Automated Marketing", "Marketing Cloud", "CRM Integration","Marketing Technology", "Martech Stack", "CDP Training","Customer Data Platform", "Identity Resolution", "Blockchain Marketing","Web3 Marketing", "DAO Marketing", "Smart Contract Marketing","Tokenomics", "Community Marketing", "Memetic Marketing","Viral Marketing", "Buzz Marketing", "Guerrilla Marketing","Experiential Marketing", "Sensory Marketing", "Holographic Marketing","Drone Marketing", "IoT Marketing", "Wearable Tech Marketing","Marketing in VR", "Marketing in AR", "Marketing in Metaverse","Phygital Marketing", "O2O Marketing", "Conversational Marketing",
  "Marketing Chatbots", "AI Copywriting", "GPT-3 for Marketing","DALL-E for Marketing", "Stable Diffusion Marketing", "AI Video Marketing","Synthetic Media", "Deepfake Marketing", "Ethical AI Marketing","Marketing Automation", "Lead Nurturing", "Drip Campaigns","Marketing Sequences", "Behavioral Targeting", "Contextual Targeting","Demographic Targeting", "Geotargeting", "Psychographic Targeting","Lookalike Audiences", "Custom Audiences", "Similar Audiences","Marketing Personalization", "Dynamic Content", "Recommendation Engines","Predictive Marketing", "Prescriptive Analytics", "Marketing AI","Machine Learning Marketing", "Big Data Marketing", "Data-Driven Marketing","Marketing Intelligence", "Competitive Intelligence", "Market Research","Consumer Insights", "Sentiment Analysis", "Social Listening","Brand Monitoring", "Trend Analysis", "Futurism in Marketing","Marketing Forecasting", "Scenario Planning", "Marketing Simulations","Gamification Marketing", "Loyalty Programs", "Rewards Marketing","Referral Marketing", "Affiliate Networks", "Influencer Networks","Marketing Partnerships", "Co-Branding", "Sponsorship Marketing","Ambush Marketing", "Grassroots Marketing", "Word-of-Mouth Marketing","Testimonial Marketing", "Case Study Marketing", "Whitepaper Marketing","Ebook Marketing", "Checklist Marketing", "Template Marketing","Toolkit Marketing", "Resource Marketing", "Educational Marketing","How-To Marketing", "Tutorial Marketing", "Guide Marketing","FAQ Marketing", "Glossary Marketing", "Dictionary Marketing","Almanac Marketing", 
  "Handbook Marketing", "Manual Marketing","Textbook Marketing", "Course Marketing", "Curriculum Marketing","Syllabus Marketing", "Lesson Plan Marketing", "Assignment Marketing","Project Marketing", "Portfolio Marketing", "Certification Marketing","Diploma Marketing", "Degree Marketing", "Micro-Credential Marketing","Badge Marketing", "Points Marketing", "Levels Marketing","Achievement Marketing", "Progress Marketing", "Milestone Marketing","Journey Marketing", "Pathway Marketing", "Roadmap Marketing","Blueprint Marketing", "Framework Marketing", "Model Marketing","Theory Marketing", "Principle Marketing", "Law Marketing","Rule Marketing", "Guideline Marketing", "Standard Marketing","Benchmark Marketing", "Metric Marketing", "Indicator Marketing","Scorecard Marketing", "Dashboard Marketing", "Report Marketing","Analysis Marketing", "Insight Marketing", "Finding Marketing","Discovery Marketing", "Research Marketing", "Study Marketing","Survey Marketing", "Poll Marketing", "Questionnaire Marketing","Interview Marketing", "Focus Group Marketing", "Observation Marketing","Experiment Marketing", "Test Marketing", "Trial Marketing","Pilot Marketing", "Prototype Marketing", "MVP Marketing","Launch Marketing", "Release Marketing", "Update Marketing","Upgrade Marketing", "Version Marketing", "Edition Marketing","Series Marketing", "Collection Marketing", "Bundle Marketing","Package Marketing", "Kit Marketing", "Set Marketing","Group Marketing", "Family Marketing", "Category Marketing","Type Marketing", "Form Marketing", "Format Marketing",
  "Style Marketing", "Theme Marketing", "Topic Marketing","Subject Marketing", "Field Marketing", "Domain Marketing","Area Marketing", "Niche Marketing", "Segment Marketing","Sector Marketing", "Industry Marketing", "Vertical Marketing","Horizontal Marketing", "B2B2C Marketing", "C2B Marketing","C2C Marketing", "G2C Marketing", "B2G Marketing", "G2B Marketing","Nonprofit Marketing", "Social Marketing", "Public Sector Marketing","Private Sector Marketing", "Hybrid Sector Marketing", "Cooperative Marketing","Collective Marketing", "Consortium Marketing", "Alliance Marketing","Partnership Marketing", "Joint Venture Marketing", "Merger Marketing","Acquisition Marketing", "Takeover Marketing", "Buyout Marketing","Investment Marketing", "Funding Marketing", "Grant Marketing","Sponsorship Marketing", "Donation Marketing", "Pledge Marketing","Crowdfunding Marketing", "ICO Marketing", "STO Marketing","IDO Marketing", "IEO Marketing", "DeFi Marketing","CeFi Marketing", "TradFi Marketing", "FinTech Marketing","EdTech Marketing", "HealthTech Marketing", "LegalTech Marketing","PropTech Marketing", "RetailTech Marketing", "FoodTech Marketing","AgriTech Marketing", "CleanTech Marketing", "GreenTech Marketing","ClimateTech Marketing", "Impact Investing Marketing", "ESG Marketing","Sustainability Marketing", "Circular Economy Marketing", "Sharing Economy Marketing","Gig Economy Marketing", "Creator Economy Marketing", "Passion Economy Marketing","Attention Economy Marketing", "Experience Economy Marketing", "Subscription Economy Marketing",
  "On-Demand Economy Marketing", "Platform Economy Marketing", "API Economy Marketing","Data Economy Marketing", "Algorithm Economy Marketing", "AI Economy Marketing","Automation Economy Marketing", "Robot Economy Marketing", "Drone Economy Marketing","Space Economy Marketing", "Ocean Economy Marketing", "BioEconomy Marketing","NeuroEconomy Marketing", "Quantum Economy Marketing", "Crypto Economy Marketing","Token Economy Marketing", "NFT Economy Marketing", "Metaverse Economy Marketing","Web3 Economy Marketing", "DAO Economy Marketing", "DeSci Marketing","DeGov Marketing", "DeSoc Marketing", "DeFi Marketing","ReFi Marketing", "GameFi Marketing", "SocialFi Marketing","LearnFi Marketing", "HealthFi Marketing", "SportFi Marketing","ArtFi Marketing", "MusicFi Marketing", "FilmFi Marketing","FashionFi Marketing", "LuxuryFi Marketing", "CollectibleFi Marketing","MemorabiliaFi Marketing", "AntiqueFi Marketing", "VintageFi Marketing","RareFi Marketing", "LimitedFi Marketing", "ExclusiveFi Marketing","EliteFi Marketing", "PremiumFi Marketing", "HighEndFi Marketing","Luxury Marketing", "Premium Marketing", "Exclusive Marketing","Elite Marketing", "High-End Marketing", "Affluent Marketing","Wealthy Marketing", "Rich Marketing", "Millionaire Marketing","Billionaire Marketing", "HNWI Marketing", "UHNWI Marketing","Private Banking Marketing", "Wealth Management Marketing", "Family Office Marketing","Philanthropy Marketing", "Charity Marketing", "Nonprofit Marketing","Social Enterprise Marketing", "Impact Investing Marketing", "ESG Investing Marketing",
  "Sustainable Investing Marketing", "Green Investing Marketing", "Clean Investing Marketing","Climate Investing Marketing", "Carbon Neutral Marketing", "Net Zero Marketing","Carbon Negative Marketing", "Climate Positive Marketing", "Regenerative Marketing","Restorative Marketing", "Healing Marketing", "Wellness Marketing","Health Marketing", "Fitness Marketing", "Nutrition Marketing","Diet Marketing", "Weight Loss Marketing", "Muscle Gain Marketing","Bodybuilding Marketing", "Yoga Marketing", "Meditation Marketing","Mindfulness Marketing", "Mental Health Marketing", "Therapy Marketing","Counseling Marketing", "Coaching Marketing", "Mentoring Marketing","Training Marketing", "Workshop Marketing", "Seminar Marketing","Webinar Marketing", "Conference Marketing", "Summit Marketing","Forum Marketing", "Roundtable Marketing", "Panel Discussion Marketing","Fireside Chat Marketing", "Keynote Marketing", "Presentation Marketing","Lecture Marketing", "Talk Marketing", "Speech Marketing","Address Marketing", "Briefing Marketing", "Debriefing Marketing","Review Marketing", "Retrospective Marketing", "Post-Mortem Marketing","Case Study Marketing", "White Paper Marketing", "Research Paper Marketing","Academic Paper Marketing", "Journal Article Marketing", "Thesis Marketing","Dissertation Marketing", "Monograph Marketing", "Treatise Marketing","Compendium Marketing", "Anthology Marketing", "Omnibus Marketing","Compilation Marketing", "Collection Marketing", "Assemblage Marketing","Aggregation Marketing", "Curation Marketing", "Exhibition Marketing",
  "Display Marketing", "Showcase Marketing", "Demonstration Marketing","Performance Marketing", "Production Marketing", "Staging Marketing","Direction Marketing", "Choreography Marketing", "Orchestration Marketing","Conducting Marketing", "Facilitation Marketing", "Moderation Marketing","Mediation Marketing", "Arbitration Marketing", "Negotiation Marketing","Diplomacy Marketing", "Statesmanship Marketing", "Leadership Marketing","Management Marketing", "Administration Marketing", "Governance Marketing","Stewardship Marketing", "Custodianship Marketing", "Guardianship Marketing","Trusteeship Marketing", "Directorship Marketing", "Chairmanship Marketing","Presidency Marketing", "Secretaryship Marketing", "Treasurership Marketing","Membership Marketing", "Fellowship Marketing", "Partnership Marketing","Associateship Marketing", "Affiliation Marketing", "Alliance Marketing","Coalition Marketing", "Federation Marketing", "Confederation Marketing","Union Marketing", "Guild Marketing", "League Marketing","Association Marketing", "Society Marketing", "Institution Marketing","Organization Marketing", "Enterprise Marketing", "Corporation Marketing","Company Marketing", "Firm Marketing", "Agency Marketing","Bureau Marketing", "Office Marketing", "Department Marketing","Division Marketing", "Unit Marketing", "Section Marketing","Branch Marketing", "Chapter Marketing", "Cell Marketing","Pod Marketing", "Hub Marketing", "Node Marketing","Network Marketing", "Web Marketing", "Mesh Marketing","Matrix Marketing", "Grid Marketing", "Lattice Marketing",
  "Framework Marketing", "Structure Marketing", "System Marketing","Ecosystem Marketing", "Biome Marketing", "Environment Marketing","Milieu Marketing", "Setting Marketing", "Context Marketing","Background Marketing", "Foreground Marketing", "Middleground Marketing","Overground Marketing", "Underground Marketing", "Mainstream Marketing","Alternative Marketing", "Underground Marketing", "Counterculture Marketing","Subculture Marketing", "Niche Marketing", "Microculture Marketing","Tribe Marketing", "Clan Marketing", "Community Marketing","Collective Marketing", "Commune Marketing", "Cooperative Marketing","Collaborative Marketing", "Participatory Marketing", "Inclusive Marketing","Equitable Marketing", "Diverse Marketing", "Multicultural Marketing","Cross-Cultural Marketing", "Intercultural Marketing", "Transcultural Marketing","Global Marketing", "International Marketing", "Multinational Marketing","Transnational Marketing", "Supranational Marketing", "Worldwide Marketing","Planetary Marketing", "Global Marketing", "Cosmic Marketing","Universal Marketing", "Galactic Marketing", "Interstellar Marketing","Intergalactic Marketing", "Multiversal Marketing", "Omniversal Marketing","Metaversal Marketing", "Hyperversal Marketing", "Transdimensional Marketing","Extradimensional Marketing", "Parallel Marketing", "Alternate Marketing","Virtual Marketing", "Augmented Marketing", "Mixed Marketing","Extended Marketing", "Enhanced Marketing", "Amplified Marketing","Intensified Marketing", "Magnified Marketing", "Multiplied Marketing","Exponential Marketing", 
  "Logarithmic Marketing", "Geometric Marketing","Arithmetic Marketing", "Linear Marketing", "Nonlinear Marketing","Chaotic Marketing", "Fractal Marketing", "Holographic Marketing","Quantum Marketing", "Relativistic Marketing", "String Marketing","M-Theory Marketing", "Loop Marketing", "Spin Marketing","Twistor Marketing", "Causal Marketing", "Acausal Marketing","Noncausal Marketing", "Retrocausal Marketing", "Precausal Marketing","Postcausal Marketing", "Metacausal Marketing", "Hypercausal Marketing","Supercausal Marketing", "Ultracausal Marketing", "Omnicausal Marketing","Pancausal Marketing", "Holocausal Marketing", "Anacausal Marketing","Paracausal Marketing", "Extracausal Marketing", "Intracausal Marketing","Circular Marketing", "Spiral Marketing", "Helical Marketing","Vortical Marketing", "Tornadic Marketing", "Cyclonic Marketing","Typhonic Marketing", "Hurricanic Marketing", "Monsoonic Marketing","Tsunamic Marketing", "Seismic Marketing", "Tectonic Marketing","Volcanic Marketing", "Magmatic Marketing", "Lava Marketing","Plasma Marketing", "Ionic Marketing", "Atomic Marketing","Molecular Marketing", "Nanoscale Marketing", "Microscale Marketing","Macroscale Marketing", "Megascale Marketing", "Gigascale Marketing","Terascale Marketing", "Petascale Marketing", "Exascale Marketing","Zettascale Marketing", "Yottascale Marketing", "Cosmic Scale Marketing","Universal Scale Marketing", "Infinite Scale Marketing", "Finite Scale Marketing","Bounded Marketing", "Unbounded Marketing", "Limited Marketing","Unlimited Marketing", "Restricted Marketing",
  "Unrestricted Marketing","Constrained Marketing", "Unconstrained Marketing", "Conditioned Marketing","Unconditioned Marketing", "Qualified Marketing", "Unqualified Marketing",
  "Certified Marketing", "Uncertified Marketing", "Accredited Marketing","Unaccredited Marketing", "Licensed Marketing", "Unlicensed Marketing","Registered Marketing", "Unregistered Marketing", "Patented Marketing","Unpatented Marketing", "Trademarked Marketing", "Untrademarked Marketing","Copyrighted Marketing", "Uncopyrighted Marketing", "Public Domain Marketing","Private Domain Marketing", "Commercial Marketing", "Noncommercial Marketing","Profit Marketing", "Nonprofit Marketing", "For-Profit Marketing","Not-For-Profit Marketing", "Charitable Marketing", "Philanthropic Marketing","Altruistic Marketing", "Humanitarian Marketing", "Benevolent Marketing","Beneficent Marketing", "Munificent Marketing", "Generous Marketing","Liberal Marketing", "Open-Handed Marketing", "Free-Handed Marketing","Big-Hearted Marketing", "Great-Hearted Marketing", "Large-Hearted Marketing","Good-Hearted Marketing", "Kind-Hearted Marketing", "Warm-Hearted Marketing","Soft-Hearted Marketing", "Tender-Hearted Marketing", "Gentle-Hearted Marketing","Lion-Hearted Marketing", "Stout-Hearted Marketing", "Brave-Hearted Marketing","Strong-Hearted Marketing", "True-Hearted Marketing", "Pure-Hearted Marketing","Clean-Hearted Marketing", "Clear-Hearted Marketing", "Bright-Hearted Marketing","Light-Hearted Marketing", "Happy-Hearted Marketing", "Joyful-Hearted Marketing","Merry-Hearted Marketing", "Jolly-Hearted Marketing", "Gay-Hearted Marketing","Blithe-Hearted Marketing", "Carefree-Hearted Marketing", "Untroubled-Hearted Marketing","Peaceful-Hearted Marketing", 
  "Placid-Hearted Marketing", "Serene-Hearted Marketing","Tranquil-Hearted Marketing", "Calm-Hearted Marketing", "Still-Hearted Marketing","Quiet-Hearted Marketing", "Silent-Hearted Marketing", "Noiseless-Hearted Marketing","Soundless-Hearted Marketing", "Hushed-Hearted Marketing", "Muted-Hearted Marketing","Soft-Hearted Marketing", "Gentle-Hearted Marketing", "Mild-Hearted Marketing","Moderate-Hearted Marketing", "Temperate-Hearted Marketing", "Balanced-Hearted Marketing","Measured-Hearted Marketing", "Restrained-Hearted Marketing", "Controlled-Hearted Marketing","Disciplined-Hearted Marketing", "Orderly-Hearted Marketing", "Methodical-Hearted Marketing","Systematic-Hearted Marketing", "Organized-Hearted Marketing", "Structured-Hearted Marketing","Planned-Hearted Marketing", "Scheduled-Hearted Marketing", "Timed-Hearted Marketing","Regular-Hearted Marketing", "Routine-Hearted Marketing", "Customary-Hearted Marketing","Habitual-Hearted Marketing", "Usual-Hearted Marketing", "Normal-Hearted Marketing","Standard-Hearted Marketing", "Typical-Hearted Marketing", "Conventional-Hearted Marketing","Traditional-Hearted Marketing", "Orthodox-Hearted Marketing", "Conservative-Hearted Marketing","Old-Fashioned-Hearted Marketing", "Outdated-Hearted Marketing", "Dated-Hearted Marketing","Passé-Hearted Marketing", "Obsolete-Hearted Marketing", "Archaic-Hearted Marketing","Old-Hearted Marketing", "Outdated-Hearted Marketing", "Dated-Hearted Marketing","Passé-Hearted Marketing", "Obsolete-Hearted Marketing", "Archaic-Hearted Marketing","Old-Hearted Marketing", 
  "Outdated-Hearted Marketing", "Dated-Hearted Marketing","Passé-Hearted Marketing", "Obsolete-Hearted Marketing", "Archaic-Hearted Marketing","Old-Hearted Marketing", "Outdated-Hearted Marketing", "Dated-Hearted Marketing"
];

export const metadata: Metadata = {
  title: "BIPS Classes - Empowering Through Education | Digital Marketing & Spoken English",
  description: "BIPS Classes offers quality training in Digital Marketing, Spoken English, Competitive Exam Preparation with expert faculty, practical training, and placement assistance.",
  keywords: keywords.join(", "),
  authors: [{ name: "BIPS Education", url: "https://bipsclasses.com" }],
  creator: "BIPS Education Team",
  publisher: "BIPS Institute",
  metadataBase: new URL("https://bipsclasses.com"),
  alternates: {
    canonical: "/",
    languages: {
      "en-US": "/en-US",
    },
  },
  openGraph: {
    title: "BIPS Classes - Professional Training Institute",
    description: "Quality education in Digital Marketing, Spoken English and Competitive Exams",
    url: "https://bipsclasses.com",
    siteName: "BIPS Classes",
    images: [
      {
        url: "https://bipsclasses.com/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "BIPS Classes Training Center",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "BIPS Classes - Empowering Through Education",
    description: "Join our professional courses to boost your career",
    images: ["https://bipsclasses.com/twitter-image.jpg"],
    site: "@bipsclasses",
    creator: "@bipseducation",
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon-16x16.png",
    apple: "/apple-touch-icon.png",
  },
  manifest: "/site.webmanifest",
  verification: {
    google: "your-google-verification-code",
    yandex: "your-yandex-verification-code",
  },
  formatDetection: {
    email: true,
    address: true,
    telephone: true,
  },
  category: "education",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="theme-color" content="#ffffff" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
      </head>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem disableTransitionOnChange>
          <Navbar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}